### ISSUE TITLE
Tracking issue for moving to Polymer/

### ISSUE THREAD

**Issue by tjsavage** [PolymerLabs/polylint#66]
- [x] Installation instructions for Atom & Sublime in the README
- [x] Make sure atom & sublime plugin pages have content
- [x] Bump version of Atom plugin
